security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                    crate_user: { password: '' }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: true
            provider: users_in_memory
            access_token:
                token_handler: App\Security\AccessTokenHandler
                token_extractors: 'App\Security\CustomTokenExtractor'

    access_control:
        - { path: ^/api/v1/crates/new$, roles: IS_AUTHENTICATED }
        - { path: ^/api/v1/crates/.+/yank$, roles: IS_AUTHENTICATED }
        - { path: ^/api/v1/crates/.+/unyank$, roles: IS_AUTHENTICATED }
        - { path: ^/api/v1/crates/.+/owners$, roles: IS_AUTHENTICATED }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
