parameters:
    registry_base_url: '%env(REGISTRY_BASE_URL)%'
    path_crates: '%env(PATH_CRATES)%'
    path_index: '%env(PATH_INDEX)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\AccessTokenHandler:
        arguments:
            $tokenPath: '%kernel.project_dir%/tokens.json'

    App\Service\CrateService:
        arguments:
            $crateDir: '%kernel.project_dir%/%path_crates%'
            $indexDir: '%kernel.project_dir%/%path_index%'